import type Database from 'better-sqlite3';
import {
  CHECKIN_STATUS,
  CONTENT_STATUS,
  DOCUMENT_TYPE,
  INCIDENT_SEVERITY,
  ORDER_STATUS,
  PARTICIPANT_SOURCE,
  PARTICIPANT_STATUS,
  PAYMENT_SOURCE,
  PAYMENT_STATUS,
  PAYMENT_TYPE,
  ROLES,
  TRIP_CATEGORY,
  TRIP_STATUS,
  VENDOR_TYPE,
  VISIBILITY_STATUS,
} from '../constants';
import { toJson } from '../utils';

function insert(db: Database.Database, table: string, row: Record<string, unknown>) {
  const columns = Object.keys(row);
  const placeholders = columns.map((column) => `@${column}`).join(', ');
  const statement = db.prepare(
    `INSERT OR IGNORE INTO ${table} (${columns.join(', ')}) VALUES (${placeholders})`
  );

  statement.run(row);
}

function syncDepartureSeatCaches(db: Database.Database, departureId: string) {
  const summary = db
    .prepare(
      `
      SELECT
        SUM(CASE WHEN participant_status IN ('reserved', 'pending_form', 'form_submitted', 'confirmed') THEN 1 ELSE 0 END) AS reserved,
        SUM(CASE WHEN participant_status IN ('form_submitted', 'confirmed') THEN 1 ELSE 0 END) AS confirmed
      FROM trip_participants
      WHERE departure_id = ?
      `
    )
    .get(departureId) as { reserved: number | null; confirmed: number | null };

  db.prepare(
    `
    UPDATE trip_departures
    SET seats_reserved = ?,
        seats_confirmed = ?,
        updated_at = CURRENT_TIMESTAMP
    WHERE id = ?
    `
  ).run(summary.reserved ?? 0, summary.confirmed ?? 0, departureId);
}

export function seedDatabase(db: Database.Database) {
  const existing = db.prepare(`SELECT COUNT(*) AS count FROM destinations`).get() as { count: number };
  if (existing.count > 0) {
    return;
  }

  const now = '2026-04-05T10:00:00.000Z';

  const seed = db.transaction(() => {
    [
      {
        id: 'dest_kodaikanal',
        name: 'Kodaikanal',
        slug: 'kodaikanal',
        short_description: 'Cloud-wrapped viewpoints, pine trails, and cold-morning campfires.',
        long_description:
          "Kodaikanal is one of UrbanDetox's signature hill escapes: early starts, soft treks, lake time, and a pace that feels adventurous without becoming chaotic.",
        hero_image: null,
        cover_gallery: toJson(['misty-ridge', 'kodai-lake', 'pine-forest']),
        region: 'Tamil Nadu Hills',
        tags: toJson(['weekend', 'trek', 'sunrise']),
        is_active: 1,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'dest_gokarna',
        name: 'Gokarna',
        slug: 'gokarna',
        short_description: 'Coastal backpacking with beach hikes, bonfire dinners, and unhurried mornings.',
        long_description:
          'Gokarna combines the easy joy of the coast with enough movement to feel like a real trip. The route works well for first-timers, friend groups, and repeat UrbanDetox travelers.',
        hero_image: null,
        cover_gallery: toJson(['om-beach', 'sunset-cove', 'beach-trail']),
        region: 'Karnataka Coast',
        tags: toJson(['beach', 'camp', 'backpacking']),
        is_active: 1,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'dest_kannur',
        name: 'Kannur',
        slug: 'kannur',
        short_description: 'Low-friction beach weekends with clean stays and easy logistics from Bangalore.',
        long_description:
          'Kannur is the smoothest short-haul beach reset in the line-up: easy boarding, soft adventure, and a great package for college groups or quick team breaks.',
        hero_image: null,
        cover_gallery: toJson(['cliff-walk', 'sunrise-beach', 'resort-stay']),
        region: 'Kerala Coast',
        tags: toJson(['weekend', 'beach', 'student']),
        is_active: 1,
        created_at: now,
        updated_at: now,
      },
    ].forEach((row) => insert(db, 'destinations', row));

    [
      {
        id: 'pkg_kodai_3d',
        destination_id: 'dest_kodaikanal',
        package_code: 'KODAI-3D',
        slug: 'kodai-3-days',
        default_name: 'Kodai 3 Days',
        duration_days: 3,
        duration_nights: 2,
        default_description:
          'The flagship Kodai trip with more room for weather changes, unhurried meals, and a stronger itinerary arc from arrival to checkout.',
        highlights_json: toJson(['Moir Point sunrise', 'Resort stay', 'Forest walk', 'Village breakfast']),
        whats_included_json: toJson(['Travel', 'Stay', 'Trip captain', '4 meals']),
        whats_not_included_json: toJson(['Adventure add-ons', 'Personal expenses']),
        default_group_size: 18,
        default_meeting_point: 'Silk Board pickup',
        difficulty_level: 'easy',
        category: TRIP_CATEGORY.WEEKEND,
        is_active: 1,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'pkg_gokarna_3d',
        destination_id: 'dest_gokarna',
        package_code: 'GOKARNA-3D',
        slug: 'gokarna-coast-trail',
        default_name: 'Gokarna Coast Trail',
        duration_days: 3,
        duration_nights: 2,
        default_description:
          'Beach trek, cafe stops, and a slower social rhythm for travelers who want coastline over crowds.',
        highlights_json: toJson(['Beach trek', 'Cliff sunset', 'Cafe crawl']),
        whats_included_json: toJson(['Travel', 'Camp stay', 'Local transfers', '2 breakfasts']),
        whats_not_included_json: toJson(['Water sports', 'Cafe spending']),
        default_group_size: 20,
        default_meeting_point: 'Nayandahalli pickup',
        difficulty_level: 'moderate',
        category: TRIP_CATEGORY.ADVENTURE,
        is_active: 1,
        created_at: now,
        updated_at: now,
      },
      {
        id: 'pkg_kannur_2d',
        destination_id: 'dest_kannur',
        package_code: 'KANNUR-2D',
        slug: 'kannur-beach-weekender',
        default_name: 'Kannur Beach Weekender',
        duration_days: 2,
        duration_nights: 1,
        default_description:
          'A reliable low-friction coastal weekender with clean rooms, easy transport, and student-friendly pricing.',
        highlights_json: toJson(['Beach sunset', 'Resort stay', 'Night walk']),
        whats_included_json: toJson(['Travel', 'Stay', 'Breakfast', 'Trip lead']),
        whats_not_included_json: toJson(['Lunch', 'Snacks']),
        default_group_size: 24,
        default_meeting_point: 'Banashankari pickup',
        difficulty_level: 'easy',
        category: TRIP_CATEGORY.STUDENT,
        is_active: 1,
        created_at: now,
        updated_at: now,
      },
    ].forEach((row) => insert(db, 'trip_packages', row));

    [
      {
        id: 'day_kodai3_1',
        package_id: 'pkg_kodai_3d',
        day_number: 1,
        title: 'Overnight departure and hill arrival',
        description: 'Leave Bangalore at night, climb into Kodai at dawn, settle into the resort, and ease into the weekend with a soft viewpoint circuit.',
        meals_json: toJson(['breakfast', 'dinner']),
        stay_type: 'Resort',
        notes: 'Weather buffer after lunch.',
        sort_order: 1,
      },
      {
        id: 'day_kodai3_2',
        package_id: 'pkg_kodai_3d',
        day_number: 2,
        title: 'Forest trail and local experiences',
        description: 'A relaxed day with breakfast outdoors, pine forest time, curated photo stops, and a flexible evening based on weather.',
        meals_json: toJson(['breakfast', 'dinner']),
        stay_type: 'Resort',
        notes: 'Optional boating in the evening.',
        sort_order: 2,
      },
      {
        id: 'day_gokarna_1',
        package_id: 'pkg_gokarna_3d',
        day_number: 1,
        title: 'Arrival and camp circle',
        description: 'Reach the coast, settle into camp, explore the first beach stretch, and gather for a beachside dinner.',
        meals_json: toJson(['dinner']),
        stay_type: 'Camp',
        notes: 'Light walk only.',
        sort_order: 1,
      },
      {
        id: 'day_kannur_1',
        package_id: 'pkg_kannur_2d',
        day_number: 1,
        title: 'Arrival and resort check-in',
        description: 'Travel in, freshen up, explore the beach zone, and keep the evening open for group games and dinner.',
        meals_json: toJson(['dinner']),
        stay_type: 'Resort',
        notes: null,
        sort_order: 1,
      },
    ].forEach((row) => insert(db, 'trip_package_days', row));

    [
      { id: 'gallery_kodai3_1', package_id: 'pkg_kodai_3d', image_url: 'kodai-cover-1', caption: 'Morning light over the valley', sort_order: 1 },
      { id: 'gallery_gokarna_1', package_id: 'pkg_gokarna_3d', image_url: 'gokarna-cover-1', caption: 'Trail between hidden beaches', sort_order: 1 },
      { id: 'gallery_kannur_1', package_id: 'pkg_kannur_2d', image_url: 'kannur-cover-1', caption: 'Evening by the waterline', sort_order: 1 },
    ].forEach((row) => insert(db, 'trip_package_gallery', row));

    [
      { id: 'profile_admin_1', full_name: 'Sameer UrbanDetox', phone: '+91 99999 11111', email: 'sameer@urbandetox.com', avatar_url: null, role: ROLES.ADMIN, status: 'active', created_at: now, updated_at: now },
      { id: 'profile_ops_1', full_name: 'Rhea Ops', phone: '+91 99999 22222', email: 'ops@urbandetox.com', avatar_url: null, role: ROLES.OPS, status: 'active', created_at: now, updated_at: now },
      { id: 'profile_content_1', full_name: 'Dev Content', phone: '+91 99999 33333', email: 'content@urbandetox.com', avatar_url: null, role: ROLES.CONTENT, status: 'active', created_at: now, updated_at: now },
      { id: 'profile_customer_1', full_name: 'Asha Nair', phone: '+91 98765 11111', email: 'asha@example.com', avatar_url: null, role: ROLES.CUSTOMER, status: 'active', created_at: now, updated_at: now },
      { id: 'profile_customer_2', full_name: 'Rahul Menon', phone: '+91 98765 22222', email: 'rahul@example.com', avatar_url: null, role: ROLES.CUSTOMER, status: 'active', created_at: now, updated_at: now },
      { id: 'profile_customer_3', full_name: 'Maya Joseph', phone: '+91 98765 33333', email: 'maya@example.com', avatar_url: null, role: ROLES.CUSTOMER, status: 'active', created_at: now, updated_at: now },
    ].forEach((row) => insert(db, 'profiles', row));

    [
      {
        id: 'guide_anu',
        profile_id: null,
        full_name: 'Anu Thomas',
        phone: '+91 90000 11111',
        email: 'anu@urbandetox.com',
        emergency_contact: '+91 90000 12345',
        bio: 'Specializes in easy-paced group handling and first-time traveler onboarding.',
        photo: null,
        status: 'active',
      },
      {
        id: 'guide_karthik',
        profile_id: null,
        full_name: 'Karthik R',
        phone: '+91 90000 22222',
        email: 'karthik@urbandetox.com',
        emergency_contact: '+91 90000 22345',
        bio: 'Leads coast trails and keeps pace consistent for mixed-experience groups.',
        photo: null,
        status: 'active',
      },
    ].forEach((row) => insert(db, 'guides', row));

    [
      {
        id: 'vendor_pine',
        vendor_type: VENDOR_TYPE.RESORT,
        business_name: 'Pine Terrace Resort',
        contact_person: 'Muthu',
        phone: '+91 90111 11111',
        email: 'pine@example.com',
        address: 'Kodaikanal',
        gst_or_tax_id: null,
        notes: 'Preferred stay partner for Kodai 3D.',
        status: 'active',
      },
      {
        id: 'vendor_coach',
        vendor_type: VENDOR_TYPE.TRANSPORT,
        business_name: 'SouthLine Travels',
        contact_person: 'Sadiq',
        phone: '+91 90111 33333',
        email: 'southline@example.com',
        address: 'Bengaluru',
        gst_or_tax_id: null,
        notes: 'Weekend departure coaches.',
        status: 'active',
      },
    ].forEach((row) => insert(db, 'vendors', row));

    insert(db, 'cancellation_policies', {
      id: 'cancel_standard_v1',
      name: 'Standard Weekend Policy',
      version: 'v1',
      summary: 'Free transfer up to 72 hours before departure. No-show is non-refundable.',
      content:
        'Cancellations made 72 hours before departure are eligible for a one-time transfer. Within 72 hours, UrbanDetox may recover non-refundable transport and stay costs.',
      created_at: now,
    });

    insert(db, 'terms_versions', {
      id: 'terms_v1',
      title: 'UrbanDetox Trip Terms',
      version: 'v1',
      content:
        'Travelers confirm that information submitted is accurate, emergency medical action may be initiated when required, and trip-lead instructions must be followed during transit and on-ground operations.',
      created_at: now,
    });

    [
      {
        id: 'dep_kodai62',
        package_id: 'pkg_kodai_3d',
        trip_code: 'KODAI62',
        public_slug: 'monsoon-reset-april-18',
        marketing_title: 'Kodai Monsoon Reset',
        subtitle: 'Cool weather, soft-paced itinerary, and a roomy 18-seat batch.',
        start_date: '2026-04-18',
        end_date: '2026-04-20',
        price: 11000,
        offer_price: 9800,
        currency: 'INR',
        group_size_max: 18,
        seats_reserved: 0,
        seats_confirmed: 0,
        guide_id: 'guide_anu',
        coordinator_id: 'profile_ops_1',
        meeting_point: 'Silk Board, Bengaluru',
        reporting_time: '21:30',
        booking_open_at: '2026-03-10T08:00:00.000Z',
        booking_close_at: '2026-04-17T20:00:00.000Z',
        cancellation_policy_id: 'cancel_standard_v1',
        terms_version_id: 'terms_v1',
        form_template_id: 'standard-onboarding-v1',
        visibility_status: VISIBILITY_STATUS.PUBLISHED,
        trip_status: TRIP_STATUS.UPCOMING,
        seasonal_override_description: 'A greener Kodai batch focused on slower outdoor time and weather-flexible stops.',
        seasonal_override_highlights_json: toJson(['Monsoon atmosphere', 'Extra photo stops', 'Indoor fallback plan']),
        cover_photo_override: null,
        is_featured: 1,
        created_by: 'profile_admin_1',
        updated_by: 'profile_admin_1',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'dep_gokarna14',
        package_id: 'pkg_gokarna_3d',
        trip_code: 'GOKARNA14',
        public_slug: 'coast-trail-may-01',
        marketing_title: 'Gokarna Coastline Escape',
        subtitle: 'A social, beach-heavy batch with a strong repeat-traveler mix.',
        start_date: '2026-05-01',
        end_date: '2026-05-03',
        price: 9500,
        offer_price: 8900,
        currency: 'INR',
        group_size_max: 20,
        seats_reserved: 0,
        seats_confirmed: 0,
        guide_id: 'guide_karthik',
        coordinator_id: 'profile_ops_1',
        meeting_point: 'Nayandahalli, Bengaluru',
        reporting_time: '22:15',
        booking_open_at: '2026-03-20T08:00:00.000Z',
        booking_close_at: '2026-04-30T18:00:00.000Z',
        cancellation_policy_id: 'cancel_standard_v1',
        terms_version_id: 'terms_v1',
        form_template_id: 'standard-onboarding-v1',
        visibility_status: VISIBILITY_STATUS.PUBLISHED,
        trip_status: TRIP_STATUS.UPCOMING,
        seasonal_override_description: 'Dry-weather trail version with longer sunset hold.',
        seasonal_override_highlights_json: toJson(['Beach trek', 'Cafe crawl', 'Cliff sunset']),
        cover_photo_override: null,
        is_featured: 1,
        created_by: 'profile_admin_1',
        updated_by: 'profile_admin_1',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'dep_kannur08',
        package_id: 'pkg_kannur_2d',
        trip_code: 'KANNUR08',
        public_slug: 'beach-weekender-march-14',
        marketing_title: 'Kannur Beach Weekender',
        subtitle: 'Completed batch used as the baseline for post-trip reporting.',
        start_date: '2026-03-14',
        end_date: '2026-03-15',
        price: 6500,
        offer_price: 6200,
        currency: 'INR',
        group_size_max: 24,
        seats_reserved: 0,
        seats_confirmed: 0,
        guide_id: 'guide_karthik',
        coordinator_id: 'profile_ops_1',
        meeting_point: 'Banashankari, Bengaluru',
        reporting_time: '22:00',
        booking_open_at: '2026-02-05T08:00:00.000Z',
        booking_close_at: '2026-03-13T19:00:00.000Z',
        cancellation_policy_id: 'cancel_standard_v1',
        terms_version_id: 'terms_v1',
        form_template_id: 'standard-onboarding-v1',
        visibility_status: VISIBILITY_STATUS.PUBLISHED,
        trip_status: TRIP_STATUS.COMPLETED,
        seasonal_override_description: null,
        seasonal_override_highlights_json: toJson([]),
        cover_photo_override: null,
        is_featured: 0,
        created_by: 'profile_admin_1',
        updated_by: 'profile_admin_1',
        created_at: now,
        updated_at: now,
      },
    ].forEach((row) => insert(db, 'trip_departures', row));

    insert(db, 'trip_departure_day_overrides', {
      id: 'override_kodai62_day2',
      departure_id: 'dep_kodai62',
      package_day_id: 'day_kodai3_2',
      title_override: 'Forest trail with monsoon shelter plan',
      description_override: 'A rain-safe version of the second day with shorter open stretches and more flexible stop timing.',
      media_override: 'rain-plan-gallery',
    });

    [
      {
        id: 'banner_home_1',
        title: 'Weekend escapes with operational clarity',
        subtitle: 'UrbanDetox is now running on a local-first booking engine so we can move fast before the Supabase cutover.',
        image_url: null,
        mobile_image_url: null,
        cta_label: 'Browse trips',
        cta_link: '/trips',
        sort_order: 1,
        active_from: now,
        active_to: null,
        is_active: 1,
      },
      {
        id: 'banner_home_2',
        title: 'Manual WhatsApp onboarding, clean data model',
        subtitle: 'Manual participants still land in the same seat ledger, so capacity, reporting, and finance stay accurate.',
        image_url: null,
        mobile_image_url: null,
        cta_label: 'See admin modules',
        cta_link: 'http://localhost:3001',
        sort_order: 2,
        active_from: now,
        active_to: null,
        is_active: 1,
      },
    ].forEach((row) => insert(db, 'home_banners', row));

    [
      {
        id: 'blog_1',
        title: 'Why departure-level pricing keeps a travel business sane',
        slug: 'departure-level-pricing-travel-ops',
        excerpt: 'A reusable package template should describe the trip shape; a departure should store the dates, live price, offer price, capacity, and booking window.',
        content:
          'Travel operations break when price is stored at the package level. A reusable package template should describe the trip shape; a departure should store the dates, live price, offer price, capacity, guide allocation, and booking window.',
        cover_image: null,
        author_id: 'profile_content_1',
        seo_title: 'Departure pricing for travel platforms',
        seo_description: 'How UrbanDetox models packages and departures cleanly.',
        status: CONTENT_STATUS.PUBLISHED,
        published_at: '2026-04-01T08:00:00.000Z',
      },
      {
        id: 'blog_2',
        title: 'Manual onboarding without breaking seat counts',
        slug: 'manual-onboarding-seat-counts',
        excerpt: 'WhatsApp bookings are useful, but only if they land in the same participant truth table as website sales.',
        content:
          'UrbanDetox keeps manual and website bookings inside a shared participant ledger. That means a manual add from ops still reduces available seats, shows up in manifest views, and flows into finance reporting instead of living in a spreadsheet shadow system.',
        cover_image: null,
        author_id: 'profile_content_1',
        seo_title: 'Manual onboarding without spreadsheet drift',
        seo_description: 'A travel ops note on manual participants and clean manifests.',
        status: CONTENT_STATUS.PUBLISHED,
        published_at: '2026-04-03T08:00:00.000Z',
      },
    ].forEach((row) => insert(db, 'blog_posts', row));

    [
      {
        id: 'guide_content_kodai',
        destination_id: 'dest_kodaikanal',
        title: 'Kodaikanal in the shoulder season',
        slug: 'kodaikanal-shoulder-season-guide',
        excerpt: 'What to wear, what changes in the itinerary, and why slower pacing matters when the hills are wetter.',
        content:
          'Shoulder season Kodai trips work best with flexible footwear, a warm layer for early morning, and a mindset that treats fog as part of the mood instead of a problem.',
        cover_image: null,
        seo_title: 'Kodaikanal shoulder season guide',
        seo_description: 'Planning tips for Kodai trips during changing weather.',
        status: CONTENT_STATUS.PUBLISHED,
        published_at: '2026-03-28T08:00:00.000Z',
      },
      {
        id: 'guide_content_gokarna',
        destination_id: 'dest_gokarna',
        title: 'How hard is the Gokarna coast trail really?',
        slug: 'gokarna-coast-trail-difficulty',
        excerpt: 'The real answer is moderate heat management, not technical difficulty.',
        content:
          'Most travelers can finish the Gokarna route if they pace the day, hydrate well, and do not treat the trek like a race.',
        cover_image: null,
        seo_title: 'Gokarna coast trail difficulty guide',
        seo_description: 'A practical read on trail pace, heat, and hydration.',
        status: CONTENT_STATUS.PUBLISHED,
        published_at: '2026-03-30T08:00:00.000Z',
      },
    ].forEach((row) => insert(db, 'travel_guides', row));

    [
      { id: 'faq_1', category: 'booking', question: 'Can I reserve a seat and complete payment later?', answer: 'In this local preview build we simulate payment instantly, but the schema already supports pending-payment expiry windows for the later gateway integration.', sort_order: 1, is_active: 1 },
      { id: 'faq_2', category: 'onboarding', question: 'How does WhatsApp onboarding work?', answer: 'Ops can add a participant manually, generate a unique onboarding token, and send the form link without creating a separate shadow record.', sort_order: 2, is_active: 1 },
      { id: 'faq_3', category: 'operations', question: 'What counts as a filled seat?', answer: 'Reserved, pending-form, form-submitted, and confirmed participants all occupy a seat. Confirmed seats are a smaller subset used for readiness reporting.', sort_order: 3, is_active: 1 },
      { id: 'faq_4', category: 'privacy', question: 'Where do uploaded documents go right now?', answer: 'For this phase they are saved locally on disk and referenced in SQLite. Later the same storage metadata can move to Supabase private buckets.', sort_order: 4, is_active: 1 },
    ].forEach((row) => insert(db, 'faqs', row));

    insert(db, 'corporate_pages', {
      id: 'corporate_page_1',
      title: 'Corporate Retreats',
      slug: 'corporate-retreats',
      content:
        'UrbanDetox runs small-group corporate retreats with the same departure discipline we use for public trips: seat counts, policy versioning, guide allocations, and clean post-trip reporting.',
      hero_image: null,
      form_config: toJson({ focus: ['team reset', 'offsite', 'wellbeing day'] }),
      is_active: 1,
    });

    insert(db, 'university_pages', {
      id: 'university_page_1',
      title: 'University Trips',
      slug: 'university-trips',
      content:
        'University batches need stricter manifest discipline, stronger parent-facing communication, and clear travel approvals. The shared participant model supports all three.',
      hero_image: null,
      form_config: toJson({ focus: ['student batch', 'faculty support', 'checklist'] }),
      is_active: 1,
    });

    [
      {
        id: 'order_kodai_1',
        departure_id: 'dep_kodai62',
        customer_profile_id: 'profile_customer_1',
        customer_name: 'Asha Nair',
        phone: '+91 98765 11111',
        email: 'asha@example.com',
        seats_requested: 2,
        subtotal: 19600,
        discount_amount: 0,
        total_amount: 19600,
        currency: 'INR',
        order_status: ORDER_STATUS.PAID,
        payment_gateway: 'preview',
        payment_reference: 'PREVIEW-KODAI-001',
        source: 'website',
        expires_at: null,
        created_at: '2026-04-02T08:15:00.000Z',
      },
      {
        id: 'order_kodai_2',
        departure_id: 'dep_kodai62',
        customer_profile_id: 'profile_customer_2',
        customer_name: 'Rahul Menon',
        phone: '+91 98765 22222',
        email: 'rahul@example.com',
        seats_requested: 1,
        subtotal: 9800,
        discount_amount: 0,
        total_amount: 9800,
        currency: 'INR',
        order_status: ORDER_STATUS.PAID,
        payment_gateway: 'preview',
        payment_reference: 'PREVIEW-KODAI-002',
        source: 'website',
        expires_at: null,
        created_at: '2026-04-03T09:20:00.000Z',
      },
      {
        id: 'order_gokarna_1',
        departure_id: 'dep_gokarna14',
        customer_profile_id: 'profile_customer_3',
        customer_name: 'Maya Joseph',
        phone: '+91 98765 33333',
        email: 'maya@example.com',
        seats_requested: 3,
        subtotal: 26700,
        discount_amount: 0,
        total_amount: 26700,
        currency: 'INR',
        order_status: ORDER_STATUS.PAID,
        payment_gateway: 'preview',
        payment_reference: 'PREVIEW-GOKARNA-001',
        source: 'website',
        expires_at: null,
        created_at: '2026-04-04T07:55:00.000Z',
      },
    ].forEach((row) => insert(db, 'booking_orders', row));

    [
      {
        id: 'participant_k62_asha',
        departure_id: 'dep_kodai62',
        booking_order_id: 'order_kodai_1',
        profile_id: 'profile_customer_1',
        source: PARTICIPANT_SOURCE.WEBSITE,
        participant_status: PARTICIPANT_STATUS.CONFIRMED,
        payment_status: PAYMENT_STATUS.PAID,
        full_name: 'Asha Nair',
        phone: '+91 98765 11111',
        email: 'asha@example.com',
        gender: 'female',
        date_of_birth: '1997-11-14',
        emergency_flag: 0,
        form_completion_percent: 100,
        added_by_admin_id: null,
        created_at: '2026-04-02T08:16:00.000Z',
        updated_at: '2026-04-02T09:00:00.000Z',
      },
      {
        id: 'participant_k62_asha_friend',
        departure_id: 'dep_kodai62',
        booking_order_id: 'order_kodai_1',
        profile_id: null,
        source: PARTICIPANT_SOURCE.WEBSITE,
        participant_status: PARTICIPANT_STATUS.PENDING_FORM,
        payment_status: PAYMENT_STATUS.PAID,
        full_name: 'Friend of Asha',
        phone: null,
        email: null,
        gender: null,
        date_of_birth: null,
        emergency_flag: 0,
        form_completion_percent: 25,
        added_by_admin_id: null,
        created_at: '2026-04-02T08:16:30.000Z',
        updated_at: '2026-04-02T08:16:30.000Z',
      },
      {
        id: 'participant_k62_rahul',
        departure_id: 'dep_kodai62',
        booking_order_id: 'order_kodai_2',
        profile_id: 'profile_customer_2',
        source: PARTICIPANT_SOURCE.WEBSITE,
        participant_status: PARTICIPANT_STATUS.FORM_SUBMITTED,
        payment_status: PAYMENT_STATUS.PAID,
        full_name: 'Rahul Menon',
        phone: '+91 98765 22222',
        email: 'rahul@example.com',
        gender: 'male',
        date_of_birth: '1995-08-21',
        emergency_flag: 0,
        form_completion_percent: 90,
        added_by_admin_id: null,
        created_at: '2026-04-03T09:21:00.000Z',
        updated_at: '2026-04-03T10:10:00.000Z',
      },
      {
        id: 'participant_k62_manual_1',
        departure_id: 'dep_kodai62',
        booking_order_id: null,
        profile_id: null,
        source: PARTICIPANT_SOURCE.MANUAL_WHATSAPP,
        participant_status: PARTICIPANT_STATUS.PENDING_FORM,
        payment_status: PAYMENT_STATUS.MANUAL_PENDING,
        full_name: 'Priya S',
        phone: '+91 98888 11111',
        email: null,
        gender: null,
        date_of_birth: null,
        emergency_flag: 0,
        form_completion_percent: 20,
        added_by_admin_id: 'profile_ops_1',
        created_at: '2026-04-04T12:00:00.000Z',
        updated_at: '2026-04-04T12:00:00.000Z',
      },
      {
        id: 'participant_g14_maya',
        departure_id: 'dep_gokarna14',
        booking_order_id: 'order_gokarna_1',
        profile_id: 'profile_customer_3',
        source: PARTICIPANT_SOURCE.WEBSITE,
        participant_status: PARTICIPANT_STATUS.CONFIRMED,
        payment_status: PAYMENT_STATUS.PAID,
        full_name: 'Maya Joseph',
        phone: '+91 98765 33333',
        email: 'maya@example.com',
        gender: 'female',
        date_of_birth: '1998-05-04',
        emergency_flag: 0,
        form_completion_percent: 100,
        added_by_admin_id: null,
        created_at: '2026-04-04T08:00:00.000Z',
        updated_at: '2026-04-04T10:00:00.000Z',
      },
      {
        id: 'participant_g14_companion_1',
        departure_id: 'dep_gokarna14',
        booking_order_id: 'order_gokarna_1',
        profile_id: null,
        source: PARTICIPANT_SOURCE.WEBSITE,
        participant_status: PARTICIPANT_STATUS.CONFIRMED,
        payment_status: PAYMENT_STATUS.PAID,
        full_name: 'Arjun Joseph',
        phone: null,
        email: null,
        gender: null,
        date_of_birth: null,
        emergency_flag: 0,
        form_completion_percent: 100,
        added_by_admin_id: null,
        created_at: '2026-04-04T08:00:10.000Z',
        updated_at: '2026-04-04T10:00:00.000Z',
      },
      {
        id: 'participant_g14_companion_2',
        departure_id: 'dep_gokarna14',
        booking_order_id: 'order_gokarna_1',
        profile_id: null,
        source: PARTICIPANT_SOURCE.WEBSITE,
        participant_status: PARTICIPANT_STATUS.FORM_SUBMITTED,
        payment_status: PAYMENT_STATUS.PAID,
        full_name: 'Nivedita P',
        phone: null,
        email: null,
        gender: null,
        date_of_birth: null,
        emergency_flag: 0,
        form_completion_percent: 80,
        added_by_admin_id: null,
        created_at: '2026-04-04T08:00:20.000Z',
        updated_at: '2026-04-04T11:00:00.000Z',
      },
      {
        id: 'participant_kannur_1',
        departure_id: 'dep_kannur08',
        booking_order_id: null,
        profile_id: null,
        source: PARTICIPANT_SOURCE.CORPORATE_BATCH,
        participant_status: PARTICIPANT_STATUS.CONFIRMED,
        payment_status: PAYMENT_STATUS.PAID,
        full_name: 'Batch Traveler 1',
        phone: null,
        email: null,
        gender: null,
        date_of_birth: null,
        emergency_flag: 0,
        form_completion_percent: 100,
        added_by_admin_id: 'profile_ops_1',
        created_at: '2026-03-10T08:00:00.000Z',
        updated_at: '2026-03-10T08:00:00.000Z',
      },
    ].forEach((row) => insert(db, 'trip_participants', row));

    [
      {
        id: 'form_asha',
        participant_id: 'participant_k62_asha',
        blood_group: 'O+',
        travel_companion_mode: 'group',
        companion_names_text: 'Friend of Asha',
        food_preferences: 'Vegetarian',
        medical_conditions_or_allergies: 'None',
        emergency_contact_name: 'Nair Joseph',
        emergency_contact_number: '+91 90000 10000',
        emergency_contact_relationship: 'Brother',
        id_proof_verified: 1,
        recent_photo_verified: 1,
        arrival_mode: 'UrbanDetox coach',
        needs_travel_assistance: 0,
        payment_completed_answer: 'Paid in full',
        waiver_accepted: 1,
        terms_accepted: 1,
        privacy_accepted: 1,
        nationality: 'Indian',
        city: 'Bengaluru',
        motion_sickness: 'No',
        swimming_skill_level: 'Basic',
        trekking_comfort_level: 'Comfortable',
        accessibility_notes: null,
        emergency_contact_alternate_number: '+91 90000 10001',
        medical_update_consent: 1,
        submitted_at: '2026-04-02T08:55:00.000Z',
        updated_at: '2026-04-02T08:55:00.000Z',
      },
      {
        id: 'form_rahul',
        participant_id: 'participant_k62_rahul',
        blood_group: 'B+',
        travel_companion_mode: 'solo',
        companion_names_text: null,
        food_preferences: 'Non-vegetarian',
        medical_conditions_or_allergies: 'Mild dust allergy',
        emergency_contact_name: 'Reena Menon',
        emergency_contact_number: '+91 90000 20000',
        emergency_contact_relationship: 'Mother',
        id_proof_verified: 0,
        recent_photo_verified: 1,
        arrival_mode: 'UrbanDetox coach',
        needs_travel_assistance: 0,
        payment_completed_answer: 'Paid in full',
        waiver_accepted: 1,
        terms_accepted: 1,
        privacy_accepted: 1,
        nationality: 'Indian',
        city: 'Bengaluru',
        motion_sickness: 'Sometimes',
        swimming_skill_level: 'No experience',
        trekking_comfort_level: 'Easy only',
        accessibility_notes: null,
        emergency_contact_alternate_number: null,
        medical_update_consent: 1,
        submitted_at: '2026-04-03T10:00:00.000Z',
        updated_at: '2026-04-03T10:00:00.000Z',
      },
      {
        id: 'form_maya',
        participant_id: 'participant_g14_maya',
        blood_group: 'A+',
        travel_companion_mode: 'group',
        companion_names_text: 'Arjun Joseph, Nivedita P',
        food_preferences: 'Eggetarian',
        medical_conditions_or_allergies: 'None',
        emergency_contact_name: 'Johan Joseph',
        emergency_contact_number: '+91 90000 30000',
        emergency_contact_relationship: 'Father',
        id_proof_verified: 1,
        recent_photo_verified: 1,
        arrival_mode: 'UrbanDetox coach',
        needs_travel_assistance: 0,
        payment_completed_answer: 'Paid in full',
        waiver_accepted: 1,
        terms_accepted: 1,
        privacy_accepted: 1,
        nationality: 'Indian',
        city: 'Kochi',
        motion_sickness: 'No',
        swimming_skill_level: 'Intermediate',
        trekking_comfort_level: 'Moderate',
        accessibility_notes: null,
        emergency_contact_alternate_number: null,
        medical_update_consent: 1,
        submitted_at: '2026-04-04T09:30:00.000Z',
        updated_at: '2026-04-04T09:30:00.000Z',
      },
    ].forEach((row) => insert(db, 'participant_forms', row));

    [
      {
        id: 'doc_asha_id',
        participant_id: 'participant_k62_asha',
        document_type: DOCUMENT_TYPE.GOVERNMENT_ID,
        storage_path: 'participant-ids/participant_k62_asha/asha-id.png',
        mime_type: 'image/png',
        uploaded_at: '2026-04-02T08:56:00.000Z',
        verified_by: 'profile_ops_1',
        verified_at: '2026-04-02T11:00:00.000Z',
      },
      {
        id: 'doc_rahul_photo',
        participant_id: 'participant_k62_rahul',
        document_type: DOCUMENT_TYPE.RECENT_PHOTO,
        storage_path: 'participant-photos/participant_k62_rahul/rahul-photo.jpg',
        mime_type: 'image/jpeg',
        uploaded_at: '2026-04-03T10:05:00.000Z',
        verified_by: 'profile_ops_1',
        verified_at: null,
      },
    ].forEach((row) => insert(db, 'participant_documents', row));

    [
      {
        id: 'onboard_priya',
        participant_id: 'participant_k62_manual_1',
        departure_id: 'dep_kodai62',
        token: 'manual-priya-kodai62',
        expires_at: '2026-04-17T20:00:00.000Z',
        used_at: null,
        created_by: 'profile_ops_1',
      },
      {
        id: 'onboard_asha_friend',
        participant_id: 'participant_k62_asha_friend',
        departure_id: 'dep_kodai62',
        token: 'asha-friend-kodai62',
        expires_at: '2026-04-17T20:00:00.000Z',
        used_at: null,
        created_by: 'profile_admin_1',
      },
    ].forEach((row) => insert(db, 'participant_onboarding_links', row));

    [
      {
        id: 'pay_kodai_1',
        departure_id: 'dep_kodai62',
        booking_order_id: 'order_kodai_1',
        participant_id: 'participant_k62_asha',
        payment_type: PAYMENT_TYPE.FULL,
        source: PAYMENT_SOURCE.PREVIEW,
        amount: 19600,
        currency: 'INR',
        status: 'success',
        external_reference: 'PREVIEW-KODAI-001',
        note: 'Simulated payment for local build.',
        paid_at: '2026-04-02T08:17:00.000Z',
        created_by: 'profile_admin_1',
      },
      {
        id: 'pay_kodai_2',
        departure_id: 'dep_kodai62',
        booking_order_id: 'order_kodai_2',
        participant_id: 'participant_k62_rahul',
        payment_type: PAYMENT_TYPE.FULL,
        source: PAYMENT_SOURCE.PREVIEW,
        amount: 9800,
        currency: 'INR',
        status: 'success',
        external_reference: 'PREVIEW-KODAI-002',
        note: 'Simulated payment for local build.',
        paid_at: '2026-04-03T09:22:00.000Z',
        created_by: 'profile_admin_1',
      },
      {
        id: 'pay_gokarna_1',
        departure_id: 'dep_gokarna14',
        booking_order_id: 'order_gokarna_1',
        participant_id: 'participant_g14_maya',
        payment_type: PAYMENT_TYPE.FULL,
        source: PAYMENT_SOURCE.PREVIEW,
        amount: 26700,
        currency: 'INR',
        status: 'success',
        external_reference: 'PREVIEW-GOKARNA-001',
        note: 'Simulated payment for local build.',
        paid_at: '2026-04-04T08:05:00.000Z',
        created_by: 'profile_admin_1',
      },
      {
        id: 'pay_manual_pending_1',
        departure_id: 'dep_kodai62',
        booking_order_id: null,
        participant_id: 'participant_k62_manual_1',
        payment_type: PAYMENT_TYPE.PARTIAL,
        source: PAYMENT_SOURCE.MANUAL,
        amount: 2000,
        currency: 'INR',
        status: 'pending',
        external_reference: null,
        note: 'Advance collected over WhatsApp.',
        paid_at: null,
        created_by: 'profile_ops_1',
      },
    ].forEach((row) => insert(db, 'payments', row));

    [
      {
        id: 'price_snap_k62',
        departure_id: 'dep_kodai62',
        old_price: 11000,
        new_price: 11000,
        old_offer_price: 10200,
        new_offer_price: 9800,
        changed_by: 'profile_admin_1',
        changed_at: '2026-03-28T10:00:00.000Z',
        reason: 'Early-bird push for April departure.',
      },
      {
        id: 'price_snap_g14',
        departure_id: 'dep_gokarna14',
        old_price: 9300,
        new_price: 9500,
        old_offer_price: 8900,
        new_offer_price: 8900,
        changed_by: 'profile_admin_1',
        changed_at: '2026-04-01T10:00:00.000Z',
        reason: 'Peak-season adjustment.',
      },
    ].forEach((row) => insert(db, 'pricing_snapshots', row));

    [
      { id: 'alloc_vendor_k62_stay', departure_id: 'dep_kodai62', vendor_id: 'vendor_pine', service_type: 'stay', agreed_cost: 42000, payment_status: 'pending', notes: '18-pax hold' },
      { id: 'alloc_vendor_k62_transport', departure_id: 'dep_kodai62', vendor_id: 'vendor_coach', service_type: 'transport', agreed_cost: 25000, payment_status: 'pending', notes: '48-seater coach reserved' },
    ].forEach((row) => insert(db, 'trip_vendor_allocations', row));

    [
      { id: 'alloc_guide_k62', departure_id: 'dep_kodai62', guide_id: 'guide_anu', role_type: 'lead_guide', payout: 6500, notes: 'Primary trip lead' },
      { id: 'alloc_guide_g14', departure_id: 'dep_gokarna14', guide_id: 'guide_karthik', role_type: 'lead_guide', payout: 6200, notes: 'Coastal batch lead' },
    ].forEach((row) => insert(db, 'trip_guide_allocations', row));

    [
      { id: 'room_k62_a', departure_id: 'dep_kodai62', room_label: 'A-101', room_type: 'Triple', vendor_id: 'vendor_pine', participant_id: 'participant_k62_asha', roommate_group_key: 'group_asha' },
      { id: 'room_k62_b', departure_id: 'dep_kodai62', room_label: 'A-101', room_type: 'Triple', vendor_id: 'vendor_pine', participant_id: 'participant_k62_asha_friend', roommate_group_key: 'group_asha' },
    ].forEach((row) => insert(db, 'trip_room_allocations', row));

    [
      { id: 'transport_k62_1', departure_id: 'dep_kodai62', vendor_id: 'vendor_coach', vehicle_name: 'Coach 1', pickup_point: 'Silk Board', seat_number: '12', participant_id: 'participant_k62_asha' },
      { id: 'transport_k62_2', departure_id: 'dep_kodai62', vendor_id: 'vendor_coach', vehicle_name: 'Coach 1', pickup_point: 'Silk Board', seat_number: '13', participant_id: 'participant_k62_asha_friend' },
    ].forEach((row) => insert(db, 'trip_transport_allocations', row));

    insert(db, 'trip_checkins', {
      id: 'checkin_kannur_1',
      departure_id: 'dep_kannur08',
      participant_id: 'participant_kannur_1',
      checkin_status: CHECKIN_STATUS.CHECKED_IN,
      checked_in_at: '2026-03-14T21:45:00.000Z',
      checked_in_by: 'profile_ops_1',
    });

    insert(db, 'trip_incidents', {
      id: 'incident_kannur_1',
      departure_id: 'dep_kannur08',
      participant_id: 'participant_kannur_1',
      severity: INCIDENT_SEVERITY.LOW,
      title: 'Minor motion sickness during return',
      description: 'Resolved with a break stop and hydration.',
      action_taken: 'Short stop, ORS, seat change.',
      reported_by: 'profile_ops_1',
      created_at: '2026-03-15T12:00:00.000Z',
    });

    [
      {
        id: 'waitlist_g14_1',
        departure_id: 'dep_gokarna14',
        name: 'Vignesh P',
        phone: '+91 97777 11111',
        email: 'vignesh@example.com',
        seats_requested: 2,
        note: 'Can join if two seats open together.',
        created_at: '2026-04-04T15:00:00.000Z',
      },
      {
        id: 'waitlist_k62_1',
        departure_id: 'dep_kodai62',
        name: 'Salma F',
        phone: '+91 97777 22222',
        email: 'salma@example.com',
        seats_requested: 1,
        note: 'Prefers window pickup.',
        created_at: '2026-04-04T17:30:00.000Z',
      },
    ].forEach((row) => insert(db, 'trip_waitlist', row));

    [
      {
        id: 'audit_departure_publish_k62',
        actor_profile_id: 'profile_admin_1',
        entity_type: 'trip_departures',
        entity_id: 'dep_kodai62',
        action: 'publish',
        before_json: toJson({ visibility_status: VISIBILITY_STATUS.DRAFT }),
        after_json: toJson({ visibility_status: VISIBILITY_STATUS.PUBLISHED }),
        created_at: '2026-03-28T11:00:00.000Z',
      },
      {
        id: 'audit_manual_participant_priya',
        actor_profile_id: 'profile_ops_1',
        entity_type: 'trip_participants',
        entity_id: 'participant_k62_manual_1',
        action: 'manual_add',
        before_json: null,
        after_json: toJson({
          source: PARTICIPANT_SOURCE.MANUAL_WHATSAPP,
          participant_status: PARTICIPANT_STATUS.PENDING_FORM,
        }),
        created_at: '2026-04-04T12:01:00.000Z',
      },
    ].forEach((row) => insert(db, 'audit_logs', row));

    ['dep_kodai62', 'dep_gokarna14', 'dep_kannur08'].forEach((departureId) =>
      syncDepartureSeatCaches(db, departureId)
    );
  });

  seed();
}
